- name: Install sshpass
  run: sudo apt-get update && sudo apt-get install -y sshpass

- name: SSH & Deploy with Password
  run: |
    sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
      cd /root/cicd/newmachine-fn
      git pull origin main
      cd /root/cicd
      docker compose build
      docker compose up -d
    EOF
